<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 13 --><!ELEMENT HealthData (ExportDate , Me , (Record | Correlation | Workout | ActivitySummary | ClinicalRecord | Audiogram | VisionPrescription)*)>
<!ATTLIST HealthData locale CDATA #REQUIRED>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate value CDATA #REQUIRED>
<!ELEMENT Me EMPTY>
<!ATTLIST Me HKCharacteristicTypeIdentifierDateOfBirth CDATA #REQUIRED>
<!ATTLIST Me HKCharacteristicTypeIdentifierBiologicalSex CDATA #REQUIRED>
<!ATTLIST Me HKCharacteristicTypeIdentifierBloodType CDATA #REQUIRED>
<!ATTLIST Me HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED>
<!ATTLIST Me HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse CDATA #REQUIRED>
<!ELEMENT Record (MetadataEntry | HeartRateVariabilityMetadataList)*>
<!ATTLIST Record type CDATA #REQUIRED>
<!ATTLIST Record unit CDATA #IMPLIED>
<!ATTLIST Record value CDATA #IMPLIED>
<!ATTLIST Record sourceName CDATA #REQUIRED>
<!ATTLIST Record sourceVersion CDATA #IMPLIED>
<!ATTLIST Record device CDATA #IMPLIED>
<!ATTLIST Record creationDate CDATA #IMPLIED>
<!ATTLIST Record startDate CDATA #REQUIRED>
<!ATTLIST Record endDate CDATA #REQUIRED>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. --><!ELEMENT Correlation (MetadataEntry | Record)*>
<!ATTLIST Correlation type CDATA #REQUIRED>
<!ATTLIST Correlation sourceName CDATA #REQUIRED>
<!ATTLIST Correlation sourceVersion CDATA #IMPLIED>
<!ATTLIST Correlation device CDATA #IMPLIED>
<!ATTLIST Correlation creationDate CDATA #IMPLIED>
<!ATTLIST Correlation startDate CDATA #REQUIRED>
<!ATTLIST Correlation endDate CDATA #REQUIRED>
<!ELEMENT Workout (MetadataEntry | WorkoutEvent | WorkoutRoute | WorkoutStatistics)*>
<!ATTLIST Workout workoutActivityType CDATA #REQUIRED>
<!ATTLIST Workout duration CDATA #IMPLIED>
<!ATTLIST Workout durationUnit CDATA #IMPLIED>
<!ATTLIST Workout totalDistance CDATA #IMPLIED>
<!ATTLIST Workout totalDistanceUnit CDATA #IMPLIED>
<!ATTLIST Workout totalEnergyBurned CDATA #IMPLIED>
<!ATTLIST Workout totalEnergyBurnedUnit CDATA #IMPLIED>
<!ATTLIST Workout sourceName CDATA #REQUIRED>
<!ATTLIST Workout sourceVersion CDATA #IMPLIED>
<!ATTLIST Workout device CDATA #IMPLIED>
<!ATTLIST Workout creationDate CDATA #IMPLIED>
<!ATTLIST Workout startDate CDATA #REQUIRED>
<!ATTLIST Workout endDate CDATA #REQUIRED>
<!ELEMENT WorkoutActivity (MetadataEntry)*>
<!ATTLIST WorkoutActivity uuid CDATA #REQUIRED>
<!ATTLIST WorkoutActivity startDate CDATA #REQUIRED>
<!ATTLIST WorkoutActivity endDate CDATA #IMPLIED>
<!ATTLIST WorkoutActivity duration CDATA #IMPLIED>
<!ATTLIST WorkoutActivity durationUnit CDATA #IMPLIED>
<!ELEMENT WorkoutEvent (MetadataEntry)*>
<!ATTLIST WorkoutEvent type CDATA #REQUIRED>
<!ATTLIST WorkoutEvent date CDATA #REQUIRED>
<!ATTLIST WorkoutEvent duration CDATA #IMPLIED>
<!ATTLIST WorkoutEvent durationUnit CDATA #IMPLIED>
<!ELEMENT WorkoutStatistics EMPTY>
<!ATTLIST WorkoutStatistics type CDATA #REQUIRED>
<!ATTLIST WorkoutStatistics startDate CDATA #REQUIRED>
<!ATTLIST WorkoutStatistics endDate CDATA #REQUIRED>
<!ATTLIST WorkoutStatistics average CDATA #IMPLIED>
<!ATTLIST WorkoutStatistics minimum CDATA #IMPLIED>
<!ATTLIST WorkoutStatistics maximum CDATA #IMPLIED>
<!ATTLIST WorkoutStatistics sum CDATA #IMPLIED>
<!ATTLIST WorkoutStatistics unit CDATA #IMPLIED>
<!ELEMENT WorkoutRoute (MetadataEntry | FileReference)*>
<!ATTLIST WorkoutRoute sourceName CDATA #REQUIRED>
<!ATTLIST WorkoutRoute sourceVersion CDATA #IMPLIED>
<!ATTLIST WorkoutRoute device CDATA #IMPLIED>
<!ATTLIST WorkoutRoute creationDate CDATA #IMPLIED>
<!ATTLIST WorkoutRoute startDate CDATA #REQUIRED>
<!ATTLIST WorkoutRoute endDate CDATA #REQUIRED>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference path CDATA #REQUIRED>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary dateComponents CDATA #IMPLIED>
<!ATTLIST ActivitySummary activeEnergyBurned CDATA #IMPLIED>
<!ATTLIST ActivitySummary activeEnergyBurnedGoal CDATA #IMPLIED>
<!ATTLIST ActivitySummary activeEnergyBurnedUnit CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleMoveTime CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleMoveTimeGoal CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleExerciseTime CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleExerciseTimeGoal CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleStandHours CDATA #IMPLIED>
<!ATTLIST ActivitySummary appleStandHoursGoal CDATA #IMPLIED>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry key CDATA #REQUIRED>
<!ATTLIST MetadataEntry value CDATA #REQUIRED>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. --><!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute)*>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute bpm CDATA #REQUIRED>
<!ATTLIST InstantaneousBeatsPerMinute time CDATA #REQUIRED>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord type CDATA #REQUIRED>
<!ATTLIST ClinicalRecord identifier CDATA #REQUIRED>
<!ATTLIST ClinicalRecord sourceName CDATA #REQUIRED>
<!ATTLIST ClinicalRecord sourceURL CDATA #REQUIRED>
<!ATTLIST ClinicalRecord fhirVersion CDATA #REQUIRED>
<!ATTLIST ClinicalRecord receivedDate CDATA #REQUIRED>
<!ATTLIST ClinicalRecord resourceFilePath CDATA #REQUIRED>
<!ELEMENT Audiogram (MetadataEntry | SensitivityPoint)*>
<!ATTLIST Audiogram type CDATA #REQUIRED>
<!ATTLIST Audiogram sourceName CDATA #REQUIRED>
<!ATTLIST Audiogram sourceVersion CDATA #IMPLIED>
<!ATTLIST Audiogram device CDATA #IMPLIED>
<!ATTLIST Audiogram creationDate CDATA #IMPLIED>
<!ATTLIST Audiogram startDate CDATA #REQUIRED>
<!ATTLIST Audiogram endDate CDATA #REQUIRED>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint frequencyValue CDATA #REQUIRED>
<!ATTLIST SensitivityPoint frequencyUnit CDATA #REQUIRED>
<!ATTLIST SensitivityPoint leftEarValue CDATA #IMPLIED>
<!ATTLIST SensitivityPoint leftEarUnit CDATA #IMPLIED>
<!ATTLIST SensitivityPoint rightEarValue CDATA #IMPLIED>
<!ATTLIST SensitivityPoint rightEarUnit CDATA #IMPLIED>
<!ELEMENT VisionPrescription (RightEye | LeftEye | Attachment | MetadataEntry)*>
<!ATTLIST VisionPrescription type CDATA #REQUIRED>
<!ATTLIST VisionPrescription dateIssued CDATA #REQUIRED>
<!ATTLIST VisionPrescription expirationDate CDATA #IMPLIED>
<!ATTLIST VisionPrescription brand CDATA #IMPLIED>
<!ELEMENT RightEye EMPTY>
<!ATTLIST RightEye sphere CDATA #IMPLIED>
<!ATTLIST RightEye sphereUnit CDATA #IMPLIED>
<!ATTLIST RightEye cylinder CDATA #IMPLIED>
<!ATTLIST RightEye cylinderUnit CDATA #IMPLIED>
<!ATTLIST RightEye axis CDATA #IMPLIED>
<!ATTLIST RightEye axisUnit CDATA #IMPLIED>
<!ATTLIST RightEye add CDATA #IMPLIED>
<!ATTLIST RightEye addUnit CDATA #IMPLIED>
<!ATTLIST RightEye vertex CDATA #IMPLIED>
<!ATTLIST RightEye vertexUnit CDATA #IMPLIED>
<!ATTLIST RightEye prismAmount CDATA #IMPLIED>
<!ATTLIST RightEye prismAmountUnit CDATA #IMPLIED>
<!ATTLIST RightEye prismAngle CDATA #IMPLIED>
<!ATTLIST RightEye prismAngleUnit CDATA #IMPLIED>
<!ATTLIST RightEye farPD CDATA #IMPLIED>
<!ATTLIST RightEye farPDUnit CDATA #IMPLIED>
<!ATTLIST RightEye nearPD CDATA #IMPLIED>
<!ATTLIST RightEye nearPDUnit CDATA #IMPLIED>
<!ATTLIST RightEye baseCurve CDATA #IMPLIED>
<!ATTLIST RightEye baseCurveUnit CDATA #IMPLIED>
<!ATTLIST RightEye diameter CDATA #IMPLIED>
<!ATTLIST RightEye diameterUnit CDATA #IMPLIED>
<!ELEMENT LeftEye EMPTY>
<!ATTLIST LeftEye sphere CDATA #IMPLIED>
<!ATTLIST LeftEye sphereUnit CDATA #IMPLIED>
<!ATTLIST LeftEye cylinder CDATA #IMPLIED>
<!ATTLIST LeftEye cylinderUnit CDATA #IMPLIED>
<!ATTLIST LeftEye axis CDATA #IMPLIED>
<!ATTLIST LeftEye axisUnit CDATA #IMPLIED>
<!ATTLIST LeftEye add CDATA #IMPLIED>
<!ATTLIST LeftEye addUnit CDATA #IMPLIED>
<!ATTLIST LeftEye vertex CDATA #IMPLIED>
<!ATTLIST LeftEye vertexUnit CDATA #IMPLIED>
<!ATTLIST LeftEye prismAmount CDATA #IMPLIED>
<!ATTLIST LeftEye prismAmountUnit CDATA #IMPLIED>
<!ATTLIST LeftEye prismAngle CDATA #IMPLIED>
<!ATTLIST LeftEye prismAngleUnit CDATA #IMPLIED>
<!ATTLIST LeftEye farPD CDATA #IMPLIED>
<!ATTLIST LeftEye farPDUnit CDATA #IMPLIED>
<!ATTLIST LeftEye nearPD CDATA #IMPLIED>
<!ATTLIST LeftEye nearPDUnit CDATA #IMPLIED>
<!ATTLIST LeftEye baseCurve CDATA #IMPLIED>
<!ATTLIST LeftEye baseCurveUnit CDATA #IMPLIED>
<!ATTLIST LeftEye diameter CDATA #IMPLIED>
<!ATTLIST LeftEye diameterUnit CDATA #IMPLIED>
<!ELEMENT Attachment EMPTY>
<!ATTLIST Attachment identifier CDATA #IMPLIED>
]>
<HealthData locale="en_US">
  <ExportDate value="2023-03-18 00:11:42 -0400"/>
  <Me HKCharacteristicTypeIdentifierDateOfBirth="1983-05-29" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet" HKCharacteristicTypeIdentifierCardioFitnessMedicationsUse="None"/>

  <!-- Step Count Records -->
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="7.0.2" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:7.0.2&gt;" unit="count" creationDate="2020-10-24 18:04:01 -0400" startDate="2020-10-24 17:56:38 -0400" endDate="2020-10-24 17:56:46 -0400" value="13"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="7.0.2" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:7.0.2&gt;" unit="count" creationDate="2020-10-24 18:05:03 -0400" startDate="2020-10-24 18:04:17 -0400" endDate="2020-10-24 18:05:00 -0400" value="54"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="7.0.2" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:7.0.2&gt;" unit="count" creationDate="2020-10-24 18:06:24 -0400" startDate="2020-10-24 18:05:03 -0400" endDate="2020-10-24 18:05:05 -0400" value="13"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="7.0.2" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:7.0.2&gt;" unit="count" creationDate="2020-10-24 18:06:24 -0400" startDate="2020-10-24 18:05:13 -0400" endDate="2020-10-24 18:06:14 -0400" value="76"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="7.0.2" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:7.0.2&gt;" unit="count" creationDate="2020-10-24 18:16:30 -0400" startDate="2020-10-24 18:06:14 -0400" endDate="2020-10-24 18:07:15 -0400" value="87"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob's iPhone" sourceVersion="16.3" unit="count" creationDate="2023-01-15 14:23:12 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:15:00 -0500" value="234"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob's iPhone" sourceVersion="16.3" unit="count" creationDate="2023-01-15 14:45:33 -0500" startDate="2023-01-15 09:15:00 -0500" endDate="2023-01-15 09:30:00 -0500" value="189"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count" creationDate="2023-01-16 10:22:45 -0500" startDate="2023-01-16 08:30:00 -0500" endDate="2023-01-16 08:45:00 -0500" value="312"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x280768050&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count" creationDate="2023-01-16 10:35:21 -0500" startDate="2023-01-16 08:45:00 -0500" endDate="2023-01-16 09:00:00 -0500" value="278"/>
  <Record type="HKQuantityTypeIdentifierStepCount" sourceName="Polar Flow" sourceVersion="4.12" unit="count" creationDate="2023-01-17 19:45:33 -0500" startDate="2023-01-17 18:00:00 -0500" endDate="2023-01-17 18:30:00 -0500" value="456"/>

  <!-- Heart Rate Records -->
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="8.5.1" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:8.5.1&gt;" unit="count/min" creationDate="2022-05-18 02:31:19 -0400" startDate="2022-05-18 02:25:42 -0400" endDate="2022-05-18 02:25:42 -0400" value="58"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="8.5.1" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:8.5.1&gt;" unit="count/min" creationDate="2022-05-18 02:37:40 -0400" startDate="2022-05-18 02:33:34 -0400" endDate="2022-05-18 02:33:34 -0400" value="59"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="8.5.1" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:8.5.1&gt;" unit="count/min" creationDate="2022-05-18 02:41:12 -0400" startDate="2022-05-18 02:40:05 -0400" endDate="2022-05-18 02:40:05 -0400" value="58.8516"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="8.5.1" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:8.5.1&gt;" unit="count/min" creationDate="2022-05-18 02:46:28 -0400" startDate="2022-05-18 02:37:30 -0400" endDate="2022-05-18 02:37:30 -0400" value="58"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="8.5.1" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,1, software:8.5.1&gt;" unit="count/min" creationDate="2022-05-18 02:46:28 -0400" startDate="2022-05-18 02:41:37 -0400" endDate="2022-05-18 02:41:37 -0400" value="59"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count/min" creationDate="2023-01-15 08:15:30 -0500" startDate="2023-01-15 08:10:15 -0500" endDate="2023-01-15 08:10:15 -0500" value="62"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count/min" creationDate="2023-01-15 08:20:45 -0500" startDate="2023-01-15 08:15:30 -0500" endDate="2023-01-15 08:15:30 -0500" value="61"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count/min" creationDate="2023-01-15 08:25:12 -0500" startDate="2023-01-15 08:20:45 -0500" endDate="2023-01-15 08:20:45 -0500" value="63"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Polar Flow" sourceVersion="4.12" unit="count/min" creationDate="2023-01-17 19:30:22 -0500" startDate="2023-01-17 18:15:00 -0500" endDate="2023-01-17 18:15:00 -0500" value="145"/>
  <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Polar Flow" sourceVersion="4.12" unit="count/min" creationDate="2023-01-17 19:35:45 -0500" startDate="2023-01-17 18:20:00 -0500" endDate="2023-01-17 18:20:00 -0500" value="152"/>

  <!-- Active Energy Burned Records -->
  <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-15 09:30:45 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:30:00 -0500" value="45.2"/>
  <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-15 10:00:22 -0500" startDate="2023-01-15 09:30:00 -0500" endDate="2023-01-15 10:00:00 -0500" value="38.7"/>
  <Record type="HKQuantityTypeIdentifierActiveEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-16 11:15:33 -0500" startDate="2023-01-16 10:45:00 -0500" endDate="2023-01-16 11:15:00 -0500" value="52.3"/>

  <!-- Basal Energy Burned Records -->
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.1" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.1&gt;" unit="Cal" creationDate="2022-11-27 18:58:43 -0400" startDate="2022-11-27 18:58:35 -0400" endDate="2022-11-27 18:58:38 -0400" value="0.086"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.1" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.1&gt;" unit="Cal" creationDate="2022-11-27 18:58:46 -0400" startDate="2022-11-27 18:58:38 -0400" endDate="2022-11-27 18:58:40 -0400" value="0.086"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.1" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.1&gt;" unit="Cal" creationDate="2022-11-27 18:58:48 -0400" startDate="2022-11-27 18:58:40 -0400" endDate="2022-11-27 18:58:43 -0400" value="0.086"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.1" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.1&gt;" unit="Cal" creationDate="2022-11-27 18:58:48 -0400" startDate="2022-11-27 18:58:43 -0400" endDate="2022-11-27 18:58:45 -0400" value="0.086"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.1" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.1&gt;" unit="Cal" creationDate="2022-11-27 18:58:53 -0400" startDate="2022-11-27 18:58:45 -0400" endDate="2022-11-27 18:58:48 -0400" value="0.086"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-15 09:00:15 -0500" startDate="2023-01-15 08:57:00 -0500" endDate="2023-01-15 09:00:00 -0500" value="2.1"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-15 09:03:22 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:03:00 -0500" value="2.1"/>
  <Record type="HKQuantityTypeIdentifierBasalEnergyBurned" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="Cal" creationDate="2023-01-15 09:06:45 -0500" startDate="2023-01-15 09:03:00 -0500" endDate="2023-01-15 09:06:00 -0500" value="2.1"/>

  <!-- Distance Walking/Running Records -->
  <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mi" creationDate="2023-01-15 09:30:45 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:30:00 -0500" value="0.45"/>
  <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mi" creationDate="2023-01-15 10:00:22 -0500" startDate="2023-01-15 09:30:00 -0500" endDate="2023-01-15 10:00:00 -0500" value="0.38"/>
  <Record type="HKQuantityTypeIdentifierDistanceWalkingRunning" sourceName="Polar Flow" sourceVersion="4.12" unit="mi" creationDate="2023-01-17 19:45:33 -0500" startDate="2023-01-17 18:00:00 -0500" endDate="2023-01-17 18:30:00 -0500" value="1.23"/>

  <!-- Body Mass Records -->
  <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Sync Solver" sourceVersion="30" unit="lb" creationDate="2023-01-10 07:30:00 -0500" startDate="2023-01-10 07:00:00 -0500" endDate="2023-01-10 07:30:00 -0500" value="175.3"/>
  <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Sync Solver" sourceVersion="30" unit="lb" creationDate="2023-01-17 07:15:00 -0500" startDate="2023-01-17 07:00:00 -0500" endDate="2023-01-17 07:15:00 -0500" value="174.8"/>
  <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Sync Solver" sourceVersion="30" unit="lb" creationDate="2023-01-24 07:20:00 -0500" startDate="2023-01-24 07:00:00 -0500" endDate="2023-01-24 07:20:00 -0500" value="175.1"/>

  <!-- Body Mass Index Records -->
  <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="Sync Solver" unit="count" creationDate="2023-01-10 07:30:00 -0500" startDate="2023-01-10 07:00:00 -0500" endDate="2023-01-10 07:30:00 -0500" value="23.8"/>
  <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="Sync Solver" unit="count" creationDate="2023-01-17 07:15:00 -0500" startDate="2023-01-17 07:00:00 -0500" endDate="2023-01-17 07:15:00 -0500" value="23.75"/>
  <Record type="HKQuantityTypeIdentifierBodyMassIndex" sourceName="Sync Solver" unit="count" creationDate="2023-01-24 07:20:00 -0500" startDate="2023-01-24 07:00:00 -0500" endDate="2023-01-24 07:20:00 -0500" value="23.79"/>

  <!-- Height Records -->
  <Record type="HKQuantityTypeIdentifierHeight" sourceName="Rob's iPhone" sourceVersion="16.3" unit="in" creationDate="2023-01-01 12:00:00 -0500" startDate="2023-01-01 00:00:00 -0500" endDate="2023-01-01 23:59:59 -0500" value="70"/>

  <!-- Flights Climbed Records -->
  <Record type="HKQuantityTypeIdentifierFlightsClimbed" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count" creationDate="2023-01-15 12:30:45 -0500" startDate="2023-01-15 12:00:00 -0500" endDate="2023-01-15 12:30:00 -0500" value="3"/>
  <Record type="HKQuantityTypeIdentifierFlightsClimbed" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count" creationDate="2023-01-15 15:15:22 -0500" startDate="2023-01-15 14:45:00 -0500" endDate="2023-01-15 15:15:00 -0500" value="2"/>
  <Record type="HKQuantityTypeIdentifierFlightsClimbed" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count" creationDate="2023-01-16 09:45:33 -0500" startDate="2023-01-16 09:00:00 -0500" endDate="2023-01-16 09:45:00 -0500" value="4"/>

  <!-- Apple Exercise Time Records -->
  <Record type="HKQuantityTypeIdentifierAppleExerciseTime" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="min" creationDate="2023-01-15 10:30:45 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 10:30:00 -0500" value="30"/>
  <Record type="HKQuantityTypeIdentifierAppleExerciseTime" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="min" creationDate="2023-01-16 11:45:22 -0500" startDate="2023-01-16 10:00:00 -0500" endDate="2023-01-16 11:45:00 -0500" value="45"/>

  <!-- Apple Stand Time Records -->
  <Record type="HKQuantityTypeIdentifierAppleStandTime" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="min" creationDate="2023-01-15 09:05:15 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:05:00 -0500" value="1"/>
  <Record type="HKQuantityTypeIdentifierAppleStandTime" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="min" creationDate="2023-01-15 10:02:33 -0500" startDate="2023-01-15 10:00:00 -0500" endDate="2023-01-15 10:02:00 -0500" value="1"/>

  <!-- VO2 Max Records -->
  <Record type="HKQuantityTypeIdentifierVO2Max" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mL/kg*min" creationDate="2023-01-17 19:50:00 -0500" startDate="2023-01-17 18:00:00 -0500" endDate="2023-01-17 19:00:00 -0500" value="42.5"/>
  <Record type="HKQuantityTypeIdentifierVO2Max" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mL/kg*min" creationDate="2023-01-20 18:30:00 -0500" startDate="2023-01-20 17:00:00 -0500" endDate="2023-01-20 18:00:00 -0500" value="43.1"/>

  <!-- Resting Heart Rate Records -->
  <Record type="HKQuantityTypeIdentifierRestingHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count/min" creationDate="2023-01-15 23:59:00 -0500" startDate="2023-01-15 00:00:00 -0500" endDate="2023-01-15 23:59:00 -0500" value="58"/>
  <Record type="HKQuantityTypeIdentifierRestingHeartRate" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="count/min" creationDate="2023-01-16 23:59:00 -0500" startDate="2023-01-16 00:00:00 -0500" endDate="2023-01-16 23:59:00 -0500" value="57"/>

  <!-- Heart Rate Variability Records -->
  <Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="ms" creationDate="2023-01-15 08:15:30 -0500" startDate="2023-01-15 08:10:00 -0500" endDate="2023-01-15 08:15:00 -0500" value="65"/>
  <Record type="HKQuantityTypeIdentifierHeartRateVariabilitySDNN" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28043ad50&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="ms" creationDate="2023-01-16 08:20:45 -0500" startDate="2023-01-16 08:15:00 -0500" endDate="2023-01-16 08:20:00 -0500" value="68"/>

  <!-- Walking Speed Records -->
  <Record type="HKQuantityTypeIdentifierWalkingSpeed" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mi/hr" creationDate="2023-01-15 09:30:45 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:30:00 -0500" value="3.2"/>
  <Record type="HKQuantityTypeIdentifierWalkingSpeed" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="mi/hr" creationDate="2023-01-16 10:15:22 -0500" startDate="2023-01-16 09:45:00 -0500" endDate="2023-01-16 10:15:00 -0500" value="3.4"/>

  <!-- Walking Step Length Records -->
  <Record type="HKQuantityTypeIdentifierWalkingStepLength" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="in" creationDate="2023-01-15 09:30:45 -0500" startDate="2023-01-15 09:00:00 -0500" endDate="2023-01-15 09:30:00 -0500" value="28.5"/>
  <Record type="HKQuantityTypeIdentifierWalkingStepLength" sourceName="Rob’s Apple Watch" sourceVersion="9.3" device="&lt;&lt;HKDevice: 0x28076f8e0&gt;, name:Apple Watch, manufacturer:Apple Inc., model:Watch, hardware:Watch6,7, software:9.3>" unit="in" creationDate="2023-01-16 10:15:22 -0500" startDate="2023-01-16 09:45:00 -0500" endDate="2023-01-16 10:15:00 -0500" value="29.1"/>

  <!-- Running Speed Records -->